---

- hosts: all
  gather_facts: true
  tasks:
    - name: Run the specified shell commmand
      shell: '{{shell}}'
      register: result

    - name: Display the outcome
      debug:
        msg: '{{ result }}'
